### ISSUE TITLE
Images missing

### ISSUE THREAD

**Issue by jullrich** [DaveL17/ZWaveNodeMatrix#1]
the plugin can not find this image:

IOError: [Errno 2] No such file or directory: u'/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoWebServer/images/controls/static/neighbors.png'

Indigo Version 2021.1. Maybe the newer version no longer has this image included? Looks like the IndigoWebServer directory is missing.

**Comment by jullrich** [comment]
Complete error message

!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! TRACEBACK !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   Z-Wave Node Matrix Error        !!! Traceback (most recent call last):
   Z-Wave Node Matrix Error        !!!   File "plugin.py", line 492, in make_the_matrix
   Z-Wave Node Matrix Error        !!!     plt.savefig(output_file, **kwarg_savefig)
   Z-Wave Node Matrix Error        !!!   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/pyplot.py", line 561, in savefig
   Z-Wave Node Matrix Error        !!!     return fig.savefig(*args, **kwargs)
   Z-Wave Node Matrix Error        !!!   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/figure.py", line 1421, in savefig
   Z-Wave Node Matrix Error        !!!     self.canvas.print_figure(*args, **kwargs)
   Z-Wave Node Matrix Error        !!!   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 2220, in print_figure
   Z-Wave Node Matrix Error        !!!     **kwargs)
   Z-Wave Node Matrix Error        !!!   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backend_bases.py", line 1962, in print_png
   Z-Wave Node Matrix Error        !!!     return agg.print_png(*args, **kwargs)
   Z-Wave Node Matrix Error        !!!   File "/System/Library/Frameworks/Python.framework/Versions/2.7/Extras/lib/python/matplotlib/backends/backend_agg.py", line 510, in print_png
   Z-Wave Node Matrix Error        !!!     filename_or_obj = open(filename_or_obj, 'wb')
   Z-Wave Node Matrix Error        !!! IOError: [Errno 2] No such file or directory: u'/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoWebServer/images/controls/static/neighbors.png'
   Z-Wave Node Matrix Error        !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
   Z-Wave Node Matrix Warning      Chart output error

**Comment by DaveL17** [comment]
The plugin itself is quite "dumb".  

The plugin will attempt to save the image to the location specified in the plugin configuration dialog--the specified location must exist, and the plugin must have authority to save to that location. You can either create the folder: 
```bash
/Library/Application Support/Perceptive Automation/Indigo 2021.1/IndigoWebServer/images/controls/static/
```
change the location specified in the plugin configuration dialog to:
```bash
/Library/Application Support/Perceptive Automation/Indigo 2021.1/Web Assets/images/controls/static/neighbors.png
```
or change the target to an existing folder. I recommend changing the location to a folder outside the Indigo folder structure to ensure that it will always be available.
